package draft

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/charlesharris/tourdesource/internal/protocol"
	"github.com/charlesharris/tourdesource/internal/store"
)

// Options configure a draft.
type Options struct {
	Root     string // repository root
	MapDir   string // directory holding map.sqlite; default <root>/.tds
	Out      string // output .tour.md path; default <root>/.tds/<project>.tour.md
	Audience string // frontmatter audience line
	Template Template
	Assemble AssembleOptions
	Warnf    func(format string, a ...any)
}

// Result summarizes a generated draft.
type Result struct {
	Path      string
	Commit    string
	Template  string
	Chapters  int
	Stops     int
	Anchors   int // stops carrying a symbol anchor
	Landmarks int
	Hotspots  int

	// seen tracks anchors already emitted, so no symbol is pointed at twice
	// across chapters.
	seen map[string]bool
}

// Generate assembles context from the map and renders a tour skeleton.
//
// Every anchor it emits names a symbol that exists in the map. Prose is left as
// TODO placeholders carrying the evidence tds has — the split is deliberate:
// choosing *what to point at* is a ranking problem the map can answer, while
// saying *why it matters* is judgment, and inventing that is what makes machine
// -written tours worthless.
func Generate(_ context.Context, opts Options) (*Result, error) {
	warnf := opts.Warnf
	if warnf == nil {
		warnf = func(string, ...any) {}
	}
	if opts.Template.Name == "" {
		opts.Template = Onboarding()
	}

	root, err := filepath.Abs(opts.Root)
	if err != nil {
		return nil, err
	}
	mapDir := opts.MapDir
	if mapDir == "" {
		mapDir = filepath.Join(root, ".tds")
	}
	sqlitePath := filepath.Join(mapDir, "map.sqlite")
	if _, err := os.Stat(sqlitePath); err != nil {
		return nil, fmt.Errorf("no map at %s: run `tds map` first", sqlitePath)
	}

	st, err := store.Open(sqlitePath)
	if err != nil {
		return nil, err
	}
	defer st.Close()

	ctx, err := Assemble(st, root, opts.Assemble)
	if err != nil {
		return nil, err
	}
	if len(ctx.Landmarks) == 0 {
		warnf("no landmarks found: the map has no class or module symbols, so the draft will be thin")
	}

	out := opts.Out
	if out == "" {
		out = filepath.Join(mapDir, ctx.ProjectName+".tour.md")
	}
	if opts.Audience == "" {
		opts.Audience = "engineers new to " + ctx.ProjectName
	}

	md, res := render(ctx, opts)
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return nil, fmt.Errorf("creating output dir: %w", err)
	}
	if err := os.WriteFile(out, md, 0o644); err != nil {
		return nil, fmt.Errorf("writing %s: %w", out, err)
	}

	res.Path = out
	return res, nil
}

// render emits the .tour.md and counts what it produced.
func render(ctx *Context, opts Options) ([]byte, *Result) {
	var b strings.Builder
	res := &Result{
		Commit:   ctx.Commit,
		Template: opts.Template.Name,
		Hotspots: len(ctx.Hotspots),
		seen:     map[string]bool{},
	}

	title := ctx.ProjectName
	if ctx.Readme.Title != "" && !strings.EqualFold(ctx.Readme.Title, ctx.ProjectName) {
		title = fmt.Sprintf("%s — %s", ctx.ProjectName, ctx.Readme.Title)
	}

	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %q\n", "A tour of "+title)
	fmt.Fprintf(&b, "template: %s\n", opts.Template.Name)
	fmt.Fprintf(&b, "audience: %q\n", opts.Audience)
	if ctx.Commit != "" {
		fmt.Fprintf(&b, "commit: %s\n", ctx.Commit)
	}
	b.WriteString("---\n\n")

	b.WriteString(draftBanner)
	b.WriteString("\n")

	if ctx.Readme.Lead != "" {
		fmt.Fprintf(&b, "%s\n\n", ctx.Readme.Lead)
		fmt.Fprintf(&b, "<!-- from %s — rewrite in your own words -->\n\n", ctx.Readme.Path)
	} else {
		b.WriteString("TODO: one paragraph on what this project is.\n\n")
	}

	for _, spec := range opts.Template.Chapters {
		fmt.Fprintf(&b, "# Chapter: %s\n\n", spec.Title)
		fmt.Fprintf(&b, "<!-- %s -->\n\n", spec.Guidance)
		res.Chapters++

		switch spec.Kind {
		case SectionOverview:
			renderOverview(&b, ctx, res)
		case SectionSlice:
			renderSlice(&b, ctx, res)
		case SectionLandmarks:
			renderLandmarks(&b, ctx, res)
		case SectionConventions:
			renderConventions(&b, ctx, res)
		case SectionSideQuests:
			renderSideQuests(&b, ctx, res)
		}
	}

	return []byte(b.String()), res
}

const draftBanner = `<!-- DRAFT generated by ` + "`tds draft`" + `.
Anchors below name symbols that exist in the map, so they resolve. The prose is
not written yet: each stop carries the evidence tds has and a TODO. Curating
this means fixing, cutting, and reordering — not starting from a blank page. -->
`

func renderOverview(b *strings.Builder, ctx *Context, res *Result) {
	if len(ctx.Languages) > 0 {
		var parts []string
		for i, l := range ctx.Languages {
			if i >= 5 {
				break
			}
			parts = append(parts, fmt.Sprintf("%s (%d files)", l.Language, l.Files))
		}
		fmt.Fprintf(b, "<!-- languages: %s -->\n\n", strings.Join(parts, ", "))
	}

	// Entrypoint counts tell a reader what kind of system this is before any
	// prose does.
	if summary := entrypointSummary(ctx); summary != "" {
		fmt.Fprintf(b, "<!-- entrypoints: %s -->\n\n", summary)
	}

	// Anchor the opening at the routes table when there is one: it is the single
	// best answer to "what can this system do?".
	if routes := ctx.Entrypoints["rails-routes"]; len(routes) > 0 {
		writeStop(b, res, routes[0].Path+":1-40", "",
			"TODO: the surface area of the app. What are the main things a user can do?")
	}
	if models := ctx.Entrypoints["rails-model"]; len(models) > 0 {
		writeStop(b, res, models[0].Path+"::"+models[0].Name, models[0].Name,
			"TODO: the central record this system is organised around, and what it represents.")
	}
}

func renderSlice(b *strings.Builder, ctx *Context, res *Result) {
	if ctx.Slice.Reason != "" {
		fmt.Fprintf(b, "<!-- proposed trace: %s -->\n\n", ctx.Slice.Reason)
	}
	if ctx.Slice.Entry == nil && len(ctx.Slice.Steps) == 0 {
		b.WriteString("<!-- tds could not propose a trace: no entrypoints in the map. -->\n\n")
		return
	}
	if e := ctx.Slice.Entry; e != nil {
		writeStop(b, res, anchorFor(e.Symbol), e.Symbol.Symbol,
			"TODO: where the operation begins. What arrives here, and what does this layer decide?")
	}
	for _, s := range ctx.Slice.Steps {
		writeStop(b, res, anchorFor(s.Symbol), s.Symbol.Symbol,
			"TODO: what happens at this step, and what it hands on. ("+s.Reason+")")
	}
}

// renderLandmarks fills the chapter to its limit, drawing from the ranked pool
// and skipping anything an earlier chapter already anchored.
func renderLandmarks(b *strings.Builder, ctx *Context, res *Result) {
	limit := ctx.LandmarkLimit
	if limit <= 0 {
		limit = len(ctx.Landmarks)
	}
	n := 0
	for _, l := range ctx.Landmarks {
		if n >= limit {
			break
		}
		if writeStop(b, res, anchorFor(l.Symbol), l.Symbol.Symbol,
			"TODO: why this exists and the one thing to know about it. ("+l.Reason+")") {
			n++
			res.Landmarks++
		}
	}
}

func renderConventions(b *strings.Builder, ctx *Context, res *Result) {
	for _, c := range ctx.Conventions {
		fmt.Fprintf(b, "**%s.** %s\n\n", c.Title, c.Detail)
	}
	if ctx.Readme.Path != "" {
		writeStop(b, res, ctx.Readme.Path+":1-30", "",
			"TODO: how to get it running locally, and anything the README gets wrong.")
	}
}

// renderSideQuests emits each side-quest as a stop that introduces it, with any
// further examples nested in a detour beneath.
//
// The shape is dictated by the format: a detour is a side-quest *from a stop*
// (chapter > stop > detour > stop), so a side-quest needs a stop to hang from.
// Leading with the most representative example and collapsing the rest reads
// better than a bare list anyway.
func renderSideQuests(b *strings.Builder, ctx *Context, res *Result) {
	for _, q := range []struct{ kind, label, prompt string }{
		{"rails-job", "background jobs", "TODO: when does work end up in a job rather than inline, and who runs them?"},
		{"rails-mailer", "outbound mail", "TODO: what does this system send, and what triggers it?"},
	} {
		eps := ctx.Entrypoints[q.kind]
		if len(eps) == 0 {
			continue
		}
		lead, rest := eps[0], eps[1:]
		if len(rest) > 3 {
			rest = rest[:3]
		}

		var extras []nestedStop
		for _, e := range rest {
			extras = append(extras, nestedStop{
				anchor: e.Path + "::" + e.Name,
				symbol: e.Name,
				prose:  "TODO: what this one does, and what triggers it.",
			})
		}
		writeStopWithDetour(b, res,
			lead.Path+"::"+lead.Name, lead.Name,
			fmt.Sprintf("**If you're working on %s.** %s", q.label, q.prompt),
			"The other "+q.label, extras)
	}

	if len(ctx.Hotspots) > 0 {
		lead := ctx.Hotspots[0]
		var sb strings.Builder
		sb.WriteString("**I'm here to fix a bug.** These files change most often, so this is where work tends to land:\n\n")
		for _, h := range ctx.Hotspots {
			sb.WriteString(fmt.Sprintf("- `%s` — %d commits", h.Path, h.Churn))
			if a := authorPhrase(h.Authors); a != "" {
				sb.WriteString(", " + a)
			}
			sb.WriteString("\n")
		}
		sb.WriteString("\nTODO: which of these are genuinely hot, and which just churn?")
		writeStop(b, res, fmt.Sprintf("%s:1-40", lead.Path), "", sb.String())
	}
}

// nestedStop is a stop to emit inside a detour.
type nestedStop struct {
	anchor string
	symbol string
	prose  string
}

// writeStopWithDetour emits a stop and, when there are extras, a detour nested
// inside it holding them — the chapter > stop > detour > stop nesting the format
// defines. With no extras it degrades to a plain stop.
func writeStopWithDetour(
	b *strings.Builder, res *Result,
	anchor, symbol, prose, detourTitle string,
	extras []nestedStop,
) {
	if res.seen[anchor] {
		return
	}
	res.seen[anchor] = true

	fmt.Fprintf(b, "::stop{anchor=%q}\n", anchor)
	fmt.Fprintf(b, "%s\n", prose)
	res.Stops++
	if symbol != "" {
		res.Anchors++
	}

	var nested []nestedStop
	for _, e := range extras {
		if res.seen[e.anchor] {
			continue
		}
		nested = append(nested, e)
	}
	if len(nested) > 0 {
		fmt.Fprintf(b, "::detour{title=%q}\n", detourTitle)
		for _, e := range nested {
			res.seen[e.anchor] = true
			fmt.Fprintf(b, "::stop{anchor=%q}\n", e.anchor)
			fmt.Fprintf(b, "%s\n", e.prose)
			b.WriteString("::\n")
			res.Stops++
			if e.symbol != "" {
				res.Anchors++
			}
		}
		b.WriteString("::\n") // close the detour
	}

	b.WriteString("::\n\n") // close the stop
}

// writeStop emits one stop directive, skipping an anchor already used earlier in
// the tour. symbol is informational — used only to decide whether the stop counts
// as symbol-anchored. Reports whether a stop was written.
func writeStop(b *strings.Builder, res *Result, anchor, symbol, prose string) bool {
	if res.seen[anchor] {
		return false
	}
	res.seen[anchor] = true

	fmt.Fprintf(b, "::stop{anchor=%q}\n", anchor)
	fmt.Fprintf(b, "%s\n", prose)
	b.WriteString("::\n\n")
	res.Stops++
	if symbol != "" {
		res.Anchors++
	}
	return true
}

// anchorFor builds the symbol anchor for a mapped symbol.
func anchorFor(s protocol.Symbol) string {
	return s.Path + "::" + s.Symbol
}

func entrypointSummary(ctx *Context) string {
	if len(ctx.Entrypoints) == 0 {
		return ""
	}
	kinds := make([]string, 0, len(ctx.Entrypoints))
	for k := range ctx.Entrypoints {
		kinds = append(kinds, k)
	}
	sort.Strings(kinds)
	parts := make([]string, 0, len(kinds))
	for _, k := range kinds {
		parts = append(parts, fmt.Sprintf("%s %d", k, len(ctx.Entrypoints[k])))
	}
	return strings.Join(parts, ", ")
}
