#!/usr/bin/env bash
#
# Bootstrap tds from a clone: check the toolchain, build the core onto PATH, and
# wire the Ruby provider so it is discovered without any environment variables.
#
# Idempotent — safe to re-run after pulling.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# Colour only when writing to a terminal, so piped or CI output stays clean.
if [ -t 1 ]; then
  bold=$(tput bold 2>/dev/null || true)
  red=$(tput setaf 1 2>/dev/null || true)
  green=$(tput setaf 2 2>/dev/null || true)
  yellow=$(tput setaf 3 2>/dev/null || true)
  reset=$(tput sgr0 2>/dev/null || true)
else
  bold="" red="" green="" yellow="" reset=""
fi

ok()   { printf "  %s✓%s %s\n" "$green" "$reset" "$1"; }
bad()  { printf "  %s✗%s %s\n" "$red" "$reset" "$1"; }
info() { printf "  %s→%s %s\n" "$yellow" "$reset" "$1"; }

# ver_ge A B — true when version A >= version B, compared numerically.
ver_ge() { [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -n1)" = "$2" ]; }

MIN_GO=1.25
MIN_RUBY=3.4
MIN_HUGO=0.128

failures=0

printf "%sChecking the toolchain%s\n" "$bold" "$reset"

# Go — builds the core.
if command -v go >/dev/null 2>&1; then
  go_ver=$(go env GOVERSION 2>/dev/null | sed 's/^go//')
  if ver_ge "${go_ver:-0}" "$MIN_GO"; then ok "go $go_ver"
  else bad "go $go_ver — need $MIN_GO+ (https://go.dev/dl/)"; failures=$((failures + 1)); fi
else
  bad "go not found — install from https://go.dev/dl/"; failures=$((failures + 1))
fi

# Ruby — runs the provider. prism ships as a default gem in 3.4, so no
# `bundle install` is needed for tds to run; the Gemfile is only for the
# provider's own tests.
if command -v ruby >/dev/null 2>&1; then
  ruby_ver=$(ruby -e 'print RUBY_VERSION' 2>/dev/null || echo 0)
  if ver_ge "$ruby_ver" "$MIN_RUBY"; then ok "ruby $ruby_ver"
  else bad "ruby $ruby_ver — need $MIN_RUBY+ for the Ruby provider (rbenv/asdf, or https://www.ruby-lang.org)"; failures=$((failures + 1)); fi
else
  bad "ruby not found — the Ruby/Rails provider needs $MIN_RUBY+ (structure maps to line ranges without it)"
  info "you can still map/build non-Ruby repos; skip with SKIP_RUBY=1"
  [ "${SKIP_RUBY:-0}" = "1" ] || failures=$((failures + 1))
fi

# Hugo — renders the site. Must be the extended build.
if command -v hugo >/dev/null 2>&1; then
  hugo_line=$(hugo version 2>/dev/null || true)
  hugo_ver=$(printf '%s' "$hugo_line" | sed -n 's/.*v\([0-9][0-9.]*\).*/\1/p')
  if ! printf '%s' "$hugo_line" | grep -q extended; then
    bad "hugo $hugo_ver is not the extended build — reinstall the extended build (brew install hugo)"; failures=$((failures + 1))
  elif ver_ge "${hugo_ver:-0}" "$MIN_HUGO"; then ok "hugo $hugo_ver (extended)"
  else bad "hugo $hugo_ver — need extended $MIN_HUGO+ (brew install hugo, or https://gohugo.io/installation/)"; failures=$((failures + 1)); fi
else
  bad "hugo not found — \`tds build\` needs extended $MIN_HUGO+ (brew install hugo, or https://gohugo.io/installation/)"; failures=$((failures + 1))
fi

if [ "$failures" -gt 0 ]; then
  printf "\n%s%d prerequisite(s) missing — install them and re-run %smake install%s\n" "$red" "$failures" "$bold" "$reset"
  exit 1
fi

# Where go install would place a binary, so tds and its provider sit together.
bindir=$(go env GOBIN)
[ -n "$bindir" ] || bindir="$(go env GOPATH)/bin"
mkdir -p "$bindir"

version=$(git describe --tags --always --dirty 2>/dev/null || echo dev)

printf "\n%sBuilding%s\n" "$bold" "$reset"
go build -ldflags "-X github.com/charlesharris/tourdesource/internal/cli.version=$version" -o "$bindir/tds" .
ok "tds $version → $bindir/tds"

# Wire the Ruby provider onto PATH. A launcher rather than a symlink so the
# provider's own lib/ resolves through its real location regardless of where it
# is called from. Discovery finds `tds-provider-ruby` on PATH with no env var.
if command -v ruby >/dev/null 2>&1 && ver_ge "$(ruby -e 'print RUBY_VERSION')" "$MIN_RUBY"; then
  launcher="$bindir/tds-provider-ruby"
  cat > "$launcher" <<EOF
#!/bin/sh
# Generated by scripts/install.sh — launches the tds Ruby provider from its
# checkout. Re-run \`make install\` after moving the repository.
exec "$repo_root/providers/ruby/exe/tds-provider-ruby" "\$@"
EOF
  chmod +x "$launcher"
  ok "tds-provider-ruby → $launcher"
fi

printf "\n%sInstalled.%s\n" "$green$bold" "$reset"
case ":$PATH:" in
  *":$bindir:"*)
    printf "Try it against another repo:\n"
    printf "  %stds map ~/src/some-repo && tds draft ~/src/some-repo && tds build ~/src/some-repo/.tds/*.tour.md --repo ~/src/some-repo%s\n" "$bold" "$reset" ;;
  *)
    info "$bindir is not on your PATH. Add it:"
    printf "      %sexport PATH=\"%s:\$PATH\"%s   # add to ~/.zshrc or ~/.bashrc\n" "$bold" "$bindir" "$reset" ;;
esac
